### ISSUE TITLE
Presence channels never get authorized

### ISSUE THREAD

**Issue by ianmurrays** [socky/socky-server-ruby#18]
Socky authenticator uses the data attribute to create the signature, and when the server tries to verify that signature it **doesn't** send the data attribute. Thus, the subscription never gets authorized.

Cheers!

**Comment by imanel** [comment]
Which version of server/authenticator are you using? Could you try on final v0.5.0?

https://github.com/socky/socky-server-ruby/blob/v0.5.0/lib/socky/server/channel/presence.rb#L36

It looks like everything is correct, and tests are confirming that.

**Comment by ianmurrays** [comment]
I'm not on final, but I had to fork and make some modifications to get it to work (both on server and authenticator). Here are my changes:

https://github.com/ianmurrays/socky-server-ruby
https://github.com/ianmurrays/socky-authenticator-ruby

**Comment by imanel** [comment]
I reviewed your changes, and saw that you completely changed idea behind channels:

https://github.com/ianmurrays/socky-authenticator-ruby/commit/c28b99061872ebe5985645545f76978218123777
User data need to be in authentication string. Otherwise user could send one valid request with one set of data to authentication server, but later on send "subscribe" request to server with completely different data - this would allow i.e. for username spoofing. I strongly believe that this change is huge security risk.

https://github.com/ianmurrays/socky-server-ruby/commit/2774c79ab92e41ed510a2320cd4fbdc3381781ab
How is it even possible that it's working for you after this change? Authenticator is required by Channel::Private and descendants. I will assume that you still have authenticator gem installed and that's why.

https://github.com/ianmurrays/socky-server-ruby/commit/3ec85b4e4c0831a7d305be04770a50837bdd96e2
Why send user info about himself? It's usually waste of bandwidth and in addition little confusing, because you already have info about yourself stored by client... Could you give me some use case for that? I'm not sure if my reasoning is valid here - that's why I'm asking :)

https://github.com/ianmurrays/socky-server-ruby/commit/e8de55a4b4fb46a96448cf666d9ead63ba62f74b
Why are you duplicating connection_id? User data is only data that was set by user(the same data that was earlier sent to authenticator) and probably should not be changed in this was...

https://github.com/ianmurrays/socky-server-ruby/commit/c9701e68c7717ec2af8ecf98cd69757b3f87d997
This one again break security policy. At default public channel are meant to only send data to not-authorized users, and receive data only from authorized(with write permission set to true) In current version you are not allowed (yet) to subscribe to public channel with authentication process(only http client is allowed to write to public channel.), but I will implement it very soon - you will then be able to force authentication and set your permissions to write. We can't allow any public member to send messages - this would result in massive flood to channel without any control. Again - this would result in security hole like calling unauthorized javascript for all clients by random person.

**Comment by ianmurrays** [comment]
Well, most of the changes I made, were thought for my specific implementation, not to fix bugs really.

> User data need to be in authentication string. Otherwise user could send one valid request with one set of data to authentication server, but later on send "subscribe" request to server with completely different data - this would allow i.e. for username spoofing. I strongly believe that this change is huge security risk.

I'm aware of the security risk, and that is why I'm handling user data independently from socky. The client JS asks the Rails server for the data for a specific connection id.

> How is it even possible that it's working for you after this change? Authenticator is required by Channel::Private and descendants. I will assume that you still have authenticator gem installed and that's why.

I made that change so I would be able to require my own version of socky-authenticator from git, since Google searches yielded no results as to how add a dependency from git on a gem. So, yeah, I'm including it separately.

> Why send user info about himself? It's usually waste of bandwidth and in addition little confusing, because you already have info about yourself stored by client... Could you give me some use case for that? I'm not sure if my reasoning is valid here - that's why I'm asking :)

I actually did that because I had a previous implementation of my webapp and that used the API from Pusher (which did send user data), and the way socky worked in that aspect broke my implementation :(

> Why are you duplicating connection_id? User data is only data that was set by user(the same data that was earlier sent to authenticator) and probably should not be changed in this was...

Unfortunately I don't remember why I did that. :(

> This one again break security policy. At default public channel are meant to only send data to not-authorized users, and receive data only from authorized(with write permission set to true) In current version you are not allowed (yet) to subscribe to public channel with authentication process(only http client is allowed to write to public channel.), but I will implement it very soon - you will then be able to force authentication and set your permissions to write. We can't allow any public member to send messages - this would result in massive flood to channel without any control. Again - this would result in security hole like calling unauthorized javascript for all clients by random person.

My webapp doesn't use public channels expect for one reason, and that is to send "heartbeats". I was having an issue where clients would go dark (lose connection or whatever), but Socky wouldn't announce it to the other clients. Using heartbeats was the only way to do this efficiently, and I was not able to write to channels from the JS API.

## 

Any comments on my changes are greatly appreciated though :) This is the best implementation of a real-time server I've found and it's been working like a charm :D

**Comment by imanel** [comment]
Ok - so except of "heartbeats" everything is clear :) I will add separate ticket to implement them in next release.

Thanks!

**Comment by ianmurrays** [comment]
Thank you for taking the time to check everything :)

Ian Murray / twitter: @synt4x / skype: ianmurrays

On 02-03-2012, at 11:14, Bernard Potocki
reply@reply.github.com
wrote:
